FROM ubuntu:18.04 as source

# install system-wide deps python
RUN apt-get -yqq update && apt-get install -yqq python-pip python3.6 python-dev libpq-dev

# copy our application code
COPY pythoncodes/requirements.txt /tmp
WORKDIR /tmp
RUN pip install -r requirements.txt

CMD ["bash"]
